# Generated by Django 3.1.4 on 2021-01-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Border',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='alphacode2',
            new_name='alpha2code',
        ),
        migrations.RemoveField(
            model_name='details',
            name='neighbouring_countries',
        ),
        migrations.AddField(
            model_name='details',
            name='borders',
            field=models.ManyToManyField(to='task.Border'),
        ),
    ]
