# Generated by Django 3.1.4 on 2021-01-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210102_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alpha2code', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('timezone', models.DateTimeField()),
                ('flag', models.ImageField(upload_to='')),
                ('borders', models.ManyToManyField(to='task.Border')),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.language')),
            ],
        ),
    ]
