# Generated by Django 3.1.4 on 2021-01-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_get'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='flag',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='details',
            name='timezone',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
