# Generated by Django 3.1.4 on 2021-01-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210104_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speak_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border', models.ManyToManyField(to='task.Border')),
                ('name', models.ManyToManyField(to='task.Language')),
            ],
        ),
    ]
