# Generated by Django 3.1.4 on 2021-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_speak_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='borders',
            field=models.ManyToManyField(to='task.Border'),
        ),
        migrations.DeleteModel(
            name='Speak_language',
        ),
    ]
