# Generated by Django 3.1.4 on 2021-01-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20210104_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='CountryDetails',
        ),
        migrations.RenameModel(
            old_name='Get',
            new_name='GetData',
        ),
    ]
